sudo: required
services: docker
language: bash
dist: bionic

env:
  global:
    - QEMU_VERSION=4.0.0-2
    - DOCKER_IMAGE="nventiveux/docker-bubbleupnpserver"
  matrix:
    - ARCH="amd64"
    - ARCH="arm32v6"

install:
- sudo apt-get update
- sudo apt-get upgrade docker-ce -Vy

before_script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- curl -SLO https://github.com/multiarch/qemu-user-static/releases/download/v${QEMU_VERSION}/qemu-arm-static.tar.gz
- tar -xzvf qemu-arm-static.tar.gz

script:
- dockerfile="${ARCH}.Dockerfile"
- if [[ "${ARCH}" == "amd64" ]]; then
      docker build -t "${DOCKER_IMAGE}:latest" -t "${DOCKER_IMAGE}:latest_${ARCH}" -f "${dockerfile}" .;
  else
      docker build -t "${DOCKER_IMAGE}:latest_${ARCH}" -f "${dockerfile}" .;
  fi
- docker images

after_success:
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
- docker push "${DOCKER_IMAGE}"
- docker logout

branches:
  only:
    - master
