sudo: required
services: docker
language: bash

env:
  global:
    - QEMU_VERSION=3.0.0
  matrix:
    - TAG=latest

install:
- sudo apt-get update
- sudo apt-get upgrade docker-ce -Vy

before_script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- curl -SLO https://github.com/multiarch/qemu-user-static/releases/download/v${QEMU_VERSION}/qemu-arm-static.tar.gz
- tar -xzvf qemu-arm-static.tar.gz

script:
- docker build -t nventiveux/docker-bubbleupnpserver:${TAG} .
- docker images

after_success:
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
- docker push nventiveux/docker-bubbleupnpserver:${TAG}

branches:
  only:
    - master
