name: Docker Image CI

on:
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '**.md'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ARCH: ['amd64', 'arm32v6', 'arm64v8']
    env:
      DOCKER_IMAGE: nventiveux/docker-bubbleupnpserver

    steps:
    - uses: actions/checkout@v2.3.4

    - name: QEMU arm32
      if: matrix.ARCH == 'arm32v6'
      env:
        QEMU_VERSION: 5.2.0-2
      run: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
        curl -SLO https://github.com/multiarch/qemu-user-static/releases/download/v${QEMU_VERSION}/qemu-arm-static.tar.gz
        tar -xzvf qemu-arm-static.tar.gz

    - name: QEMU arm64
      if: matrix.ARCH == 'arm64v8'
      env:
        QEMU_VERSION: 5.2.0-2
      run: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
        curl -SLO https://github.com/multiarch/qemu-user-static/releases/download/v${QEMU_VERSION}/qemu-aarch64-static.tar.gz
        tar -xzvf qemu-aarch64-static.tar.gz

    - name: Hadolint
      uses: brpaz/hadolint-action@v1.2.1
      with:
        dockerfile: ${{ matrix.ARCH }}.Dockerfile

    - name: Build
      run: |
        docker build -t "${DOCKER_IMAGE}:latest_${{ matrix.ARCH }}" -f "${{ matrix.ARCH }}.Dockerfile" .
        docker images

    - name: Push
      run: |
        docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker push "${DOCKER_IMAGE}:latest_${{ matrix.ARCH }}"
        docker logout
