name: Docker Image CI

on:
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '**.md'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/setup-qemu-action@v1

    - uses: docker/setup-buildx-action@v1

    - name: Hadolint
      uses: brpaz/hadolint-action@v1.2.1
      with:
        dockerfile: Dockerfile

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64,linux/arm
        push: true
        tags: nventiveux/docker-bubbleupnpserver:latest
